TeschaBooks/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from users.views import about

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('books.urls')),
    url(r'^accounts/', include('users.urls')),
    url(r'^about/', about, name='about'),
    url(r'comments/', include('comments.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.conf.urls import url
from .views import index, book_detail, UploadBook, book_edit, book_remove, book_draft_list, book_publish, comment_approve, comment_remove
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^book-detail/(?P<slug>[\w-]+)/$', book_detail, name='book_detail'),
    url(r'^upload/$', UploadBook, name='UploadBook'),
    url(r'^(?P<slug>[\w-]+)/edit/$', book_edit, name='book_edit'),
    url(r'^(?P<slug>[\w-]+)/remove/$', book_remove, name='book_remove'),
    url(r'^draft/$', book_draft_list, name='book_draft_list'),
    url(r'^(?P<slug>[\w-]+)/publish/$', book_publish, name='book_publish'),
    url(r'^comment/(?P<pk>\d+)/approve/$', comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', comment_remove, name='comment_remove'),

]

books/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from taggit.managers import TaggableManager
# Create your models here.

def upload_location(instance, filename):
    return "%s/%s" %(instance.owner, filename)

def validate_file_extension(value):
    if not value.name.endswith('.pdf'):
        raise ValidationError("Formato de archivo no permitido")

class Category(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")
    title = models.CharField(max_length=200, verbose_name='Title', null=True, blank=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return self.title

class Book(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    autor = models.CharField(max_length=200)
    description = models.TextField()
    likes = models.PositiveIntegerField(default=0)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    files = models.FileField(upload_to=upload_location, validators=[validate_file_extension])
    book_type = models.ForeignKey(Category, verbose_name='Category', null=True, blank=True)
    tags = TaggableManager()
    comment = models.ForeignKey('comments.Comment', related_name='books', null=True, blank=True)

#Definimos la funcion para publicar el libro
    def publish(self):
        self.published_date = timezone.now()
        self.save()
#Mostramos el titulo del libro en un lenguaje humano
    def __unicode__(self):
        return "%s" %(self.title)

    # Aqui va el get_absolute_url
    def get_absolute_url(self):
        return reverse("book_detail", kwargs={'slug': self.slug})
#Creamos una funcion "create_slug" para crear el Slug que se va a guardar
#en la base de datos y a la cual se le asignara a nuestro libro
def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Book.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first.id)
        return create_slug(instance, new_slug=new_slug)
    return slug
#Mandamos a llamar el metodo "pre_save" para hacer una funcion antes de
#guardar el slug
def pre_save_book_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_book_receiver, sender=Book)

books/forms.py
from django import forms
from .models import Book

class New_Book_Form(forms.ModelForm):
    title = forms.CharField(label="Titulo", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Python For Noobs'}))
    autor = forms.CharField(label="Autor(es)", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Guido Van Rossum'}))
    description = forms.CharField(label="Descripcion", min_length=150, widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Cuentanos un poco de que trata... Minimo 150 caracteres'}))
    files = forms.FileField(label="Sube tu archivo", widget=forms.FileInput(attrs={'class': 'file'}))
    tags = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Coding, Gaming, Eating'}))
    class Meta:
        model = Book
        fields = ('title', 'autor', 'description', 'files', 'book_type', 'tags')

books/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse
from .models import Book, Category
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.views.generic import CreateView
from .forms import New_Book_Form
from django.contrib.auth.models import User

# Create your views here.

def index(request):
    books_list = Book.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    cate = Category.objects.all()
    query = request.GET.get('q')
    if query:
        books_list = books_list.filter(
            Q(title__icontains=query)|
            Q(description__icontains=query)|
            Q(autor__icontains=query)|
            Q(owner__first_name__icontains=query)|
            Q(owner__last_name__icontains=query)
            ).distinct()
    page = request.GET.get('page', 1)
    paginator = Paginator(books_list, 10)
    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)
    return render(request, 'index.html', {'books':books, 'cate':cate})

from comments.forms import CommentForm
from comments.models import Comment

@login_required
def book_detail(request, slug=None):
    book = get_object_or_404(Book, slug=slug)
    comments = Comment.objects.all()
    form = CommentForm()
    return render(request, 'books/books_detail.html', {'book':book, 'form':form, 'comments':comments})

@login_required
def UploadBook(request):
    saved = False
    if request.method == 'POST':
        form = New_Book_Form(request.POST or None, request.FILES or None)
        if form.is_valid():
            book = form.save(commit=False)
            # book.published_date = timezone.now()
            book.owner = request.user
            book.save()
            saved = True
            form.save_m2m()
            return redirect('/draft')
    else:
        form = New_Book_Form()
    return render(request, 'books/upload_form.html', {'form':form})

@login_required
def book_edit(request, slug=None):
    book = get_object_or_404(Book, slug=slug)
    if request.method == 'POST':
        form = New_Book_Form(request.POST, request.FILES, instance=book)
        if form.is_valid():
            book = form.save(commit=False)
            book.owner = request.user
            book.save()
            return redirect('book_detail', slug=slug)
    else:
        form = New_Book_Form(instance=book)
    return render(request, 'books/book_edit.html', {'form':form})

@login_required
def book_remove(request, slug=None):
    book = get_object_or_404(Book, slug=slug)
    book.delete()
    return redirect('/')

@login_required
def book_draft_list(request):
    book = Book.objects.filter(published_date__isnull=True).order_by('-created_date')
    category = Category.objects.all()
    return render(request, 'books/book_draft_list.html', {'book': book, 'category':category})

@login_required
def book_publish(request, slug=None):
    book = get_object_or_404(Book, slug=slug)
    book.publish()
    return redirect('book_detail', slug=slug)

from comments.models import Comment

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approved()
    return redirect('book_detail', slug=comment.book.slug)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    book_pk = comment.book.slug
    comment.delete()
    return redirect('book_detail', slug=book_pk)

templates/books/book_draft_list.html
{% extends 'base.html' %}

{% block title %} Borrador - {{request.user.username}} {% endblock title %}

{% load taggit_templatetags2_tags %}

{% block content %}
  {% for books in book %}
    {% if books.owner == request.user %}
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-primary">
      <div class="panel-body">
        <div>
          <h3><a href="{% url 'book_detail' slug=books.slug %}" id="abook">{{books.title}}</a></h3>
          <p class="published_by">Por: {{books.owner.get_full_name}}</p>
          <p>{{books.description|truncatechars:200}}</p>
        </div>
      </div>
      <div class="panel-footer">

        <ul class="list-inline">

            <li>{{category.title}}</li>

        </ul>
      </div>
    </div>
  </div>
    {% endif %}
  <style type="text/css">
    .panel-primary{
      margin-top: 110px;
    }
    .published_by{
      font-size: 13px;
      font-style: italic;
    }
    .panel-primary{
      border: 10px;
    }
  </style>
{% endfor %}
{% endblock content %}

templates/books/book_edit.html
{% extends 'base.html' %}

{% block title %} Editar {{book.title}} {% endblock title %}

{% load widget_tweaks %}

{% block content %}
<div class="container" id="cont">
  <div class="row">
    <div class="col-sm-8 col-md-offset-2">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success"><span class="fa fa-pencil fa-lg"></span> Actualizar</button>
      </form>
    </div>
  </div>
</div>

<style type="text/css">
#cont{
  margin-top: 100px;
  background-color: #fff;
  border-radius: 10px;
  padding: 10px 10px 10px 10px;

}
#id_book_type {
    border: 1px solid #ccc;
    width: 200px;
    border-radius: 3px;
    overflow: hidden;
}

#id_book_type select {
    padding: 5px 8px;
    width: 130%;
    border: none;
    box-shadow: none;
    background: transparent;
    background-image: none;
    -webkit-appearance: none;
}

.#id_book_type select:focus {
    outline: none;
}
.btn-success{
  background-color: green;
  border-color: green;
  width: 250px;
  margin-bottom: 10px;
}
</style>
{% endblock content %}

templates/books/books_detail.html
{% extends 'base.html' %}

{% block title %} {{book.title}} {% endblock title %}

{% block content %}
  <div class="book">
    <div class="jumbotron">

      <div class="actions">
        {% if book.owner == request.user %}
        <a href="{% url 'book_edit' slug=book.slug %}" class="btn btn-info"><span class="fa fa-pencil-square-o fa-lg"></span> Editar</a>
        <a href="{% url 'book_remove' slug=book.slug %}" class="btn btn-danger"><span class="fa fa-trash-o fa-lg"></span> Borrar</a>
        {% endif %}
        {% if book.published_date %}
          <div class="date">
            {{book.published_date}}
          </div>
        {% else %}
          <a href="{% url 'book_publish' slug=book.slug %}" class="btn btn-success"><span class="fa fa-pencil fa-lg"></span> Publicar</a>
        {% endif %}
      </div>
      <h2 class="b_d_title">{{book.title}}</h2>
      <p class="book_autor">Autor: {{book.autor}}</p>
      <p class="book_description">{{book.description}}</p>
      <div class="buttonn">
        <a href="{{book.files.url}}" class="btn btn-primary">Ver <span class="fa fa-eye fa-lg"></span> </a>
      </div>
    </div>
  </div>

  <!-- Comentarios -->
<div class="container">
  <div class="row">
  <div class="col-md-6 comment" style="text-align: center;">
    {% include 'comments/add_comment_to_book.html' %}
  </div>
{% for comment in comments %}

  {% if book.id == comment.book.id %}

    {% if user.is_authenticated or comment.approved_comment %}
    <div class="col-sm-6 col-sm-offset-1">
      <div class="media-body">
          <div class="well well-lg">
            <div class="avatar">
              <img src="{{comment.user.profile.pic.thumbnail.url}}" class="img-responsive img-circle" alt="">
            </div>
            {% if not comment.approved_comment %}
            {% if book.owner == request.user %}
            <div class="btb-actions">
                <a href="{% url 'comment_remove' pk=comment.pk %}" class="btn btn-warning"><span class="glyphicon glyphicon-remove"></span></a>
                <a href="{% url 'comment_approve' pk=comment.pk %}" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span></a>
            </div>
            {% endif %}
            {% endif %}

              <h4 class="media-heading text-uppercase reviews">{{comment.user.get_full_name}} </h4>
              <ul class="media-date text-uppercase reviews list-inline">
                <li>{{comment.created_date}}</li>
              </ul>
              <p class="media-comment">
                  {{comment.text}}
              </p>
              <a class="btn btn-info btn-circle text-uppercase" href="#" id="reply"><span class="glyphicon glyphicon-share-alt"></span> Reply</a>
              <a class="btn btn-warning btn-circle text-uppercase" data-toggle="collapse" href="#replyOne"><span class="glyphicon glyphicon-comment"></span> 2 comments</a>
          </div>
      </div>
    </div>
    {% endif %}

  {% endif %}

{% endfor %}
  </div>
</div>
  <style type="text/css">
  .btb-actions{
    float: right
  }
  .comment{
    margin-bottom: 15px;
  }
  .actions{
    text-align: center;
  }
  .btn-success{
    background-color: green;
    border-color: green;
  }
    .book{
      margin-top: 100px;
    }
    .b_d_title{
      text-align: center;
    }
    .book_autor{
      text-align: center;
    }
    .book_description{
      text-align: center;
    }
    .buttonn{
      text-align: center;
    }
    .avatar img{
      float: left;
      padding-top: 5px;
      padding-bottom: 5px;
      padding-right: 5px;
    }
  </style>

{% endblock content %}

templates/books/list_ajax.html
{% load taggit_templatetags2_tags %}
{% for book in books %}

<div class="panel panel-primary">
  <div class="panel-body">
    <div>
      <a href="{% url 'book_detail' slug=book.slug %}" id="abook">{{book.title}}</a>
      <p class="published_by">Por: {{book.owner.get_full_name}}</p>
      <p>{{book.description|truncatechars:200}}</p>
    </div>
  </div>
  <div class="panel-footer">
    <ul class="list-inline">
        <a href=""><li>{{book.book_type.title}}</li></a>
    </ul>
  </div>
</div>
<style type="text/css">
  .published_by{
    font-size: 13px;
    font-style: italic;
  }
  .panel-primary{
    border: 10px;
  }
</style>
{% endfor %}

templates/books/upload_complete.html
{% extends 'base.html' %}

{% block title %} Genial - Nuevos libros {% endblock title %}

{% block content %}
<div class="container">
  <div class="row" id="contenedor">
    <h1>Se añadio un nuevo recurso satisfactoriamente! - Gracias por compartir!</h1>
  </div>
</div>
{% endblock content %}

templates/books/upload_form.html
{% extends 'base.html' %}

{% block title %} Subir nuevo archivo {% endblock title %}

{% block content %}
<div class="container" id="upload-form">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Sube un nuevo recurso</h1><br>
      <form id="body-form" role="form" action="{% url 'UploadBook' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
            {{form.as_p}}
          <input type="submit" value="Subir" class="btn btn-success">
      </form>
    </div>
  </div>
</div>
 <style type="text/css" media="screen">

  .btn-success{
    background-color: green;
    border-color: green;
    width: 250px;
  }
  #upload-form{
    background-color: #fff;
    padding: 15px 15px 15px 15px;
    box-shadow: 3px 3px 15px #2f2f2f;
  }
  #body-form{
    margin-top: 25px;
  }

 </style>
{% endblock content %}